config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :tasks, only: [:index, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :task, presence: true, length: { maximum: 120 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:edit, :update, :destroy]

    def index
        @tasks = Task.select(:id, :task, :user_id).where(user_id: current_user.id)
        @input_task = Task.new
        @no_tasks_message = "タスクが登録されていません。" if @tasks.empty?
    end

    def create
        begin
            @task = Task.new(task_params)
            @task.save!
        rescue ActiveRecord::RecordInvalid => e
            p e
            redirect_to tasks_path, flash: { error: e.message}
            format.html { redirect_to tasks_path, flash: { error: e.message} }
            format.json { render error: e.message }
        end
        respond_to do |format|
            format.html { redirect_to tasks_path }
            format.json { render json: @task }
        end
    end

    def edit
    end

    def update
        begin
            @current_task.update!(task_params)
        rescue ActiveRecord::RecordInvalid => e
            p e
            redirect_to edit_task_path(@current_task.id), flash: { error: e.message } and return
        end
        redirect_to tasks_path and return
    end

    def destroy
        begin
            @current_task.destroy! if @current_task.user_id == current_user.id
        rescue ActiveRecord::RecordInvalid => e
            p e
            redirect_to tasks_path, flash: { error: e.message } and return
        end
        redirect_to tasks_path and return
    end

    private
    def task_params
        params.require(:task).permit(:task, :user_id).merge(user_id: current_user.id)
    end

    def set_task
        @current_task = Task.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        redirect_to tasks_path if user_signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'utils/utils' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# サインインしてなければログイン画面に遷移 %>
    <%= render "shared/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if flash[:error].present? %>
    <div class="error-message">
        <h3 style="color: red"><%= flash[:error] %></h3>
    </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with(model: task_model, local: true, class: "form js-form" ) do |f| %>
  <%= f.text_field :task, class: "js-task" , placeholder: "タスクを入力してください", class: "input" %>
  <%= f.submit "登録", class: "js-submit" %>
<% end %>

app/views/shared/_header.html.erb
<header>
    <nav>
        <h1 class="title">タスク管理</h1>
        <div class="header">
            <% if user_signed_in? %>
                <div class="header-user-name">
                    <h1>こんにちは、<%= current_user.name %>さん！</h1>
                </div>
                <div class="header-logout">
                    <%= link_to destroy_user_session_path, method: :delete do %>
                        <button>ログアウト</button>
                    <% end %>
                </div>
            <% end %>
        </div>
    </nav>
</header>

app/views/tasks/edit.html.erb
<h1 class="title">タスク編集</h1>

<%# エラーメッセージ %>
<%= render "shared/error_message" %>

<%# フォーム %>
<div class="edit-form">
    <%= render "shared/form", task_model: @current_task %>
    <%= link_to tasks_path do %>
        <button>戻る</button>
    <% end %>
</div>

app/views/tasks/index.html.erb
<%# フォーム %>
<%# <div class="input-form"> %>
  <%= render "shared/form", task_model: @input_task %>
<%# </div> %>

<%# エラーメッセージ %>
<div class="error-message">
  <%= render "shared/error_message" %>
</div>

<div class="table-block">
  <table>
    <thead>
      <tr>
        <th>タスク一覧</th>
      </tr>
    </thead>

    <tbody class="tasklist-task">
      <% @tasks.each do |task| %>
          <tr>
              <td>
                <%= task.task %>
                <%= link_to edit_task_path(task.id) do %>
                  <button>編集</button>
                <% end%>
                <%= link_to task_path(task.id), method: :delete do %>
                  <button>削除</button>
                <% end%>
              </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%# タスクが存在しない場合 %>
<% if @no_tasks_message.present? %>
    <span><%= @no_tasks_message %></span>
<% end %>

app/views/top/index.html.erb
<h1>タスク管理を始める</h1>

<div>
    <%= link_to 'ログイン', new_user_session_path %>
</div>
<div>
    <%= link_to '新規登録', new_user_registration_path %>
</div>